[@b.head/]
  [@b.toolbar title="新建和修改产品"]
    bar.addBack();
  [/@]
  [@b.form name="productForm" action=b.rest.save(product) theme="list"]
    [@b.textfield label="代码" name="product.productCode" value=(product.productCode)! required="true" maxlength="10" style="width:50px"/]
    [@b.textfield label="内部编码" name="product.code" value=(product.code)! required="true" maxlength="100" /]
    [@b.textfield label="客户" name="product.customCode" value=(product.customCode?html)! required="true" /]
    [@b.textfield label="名称" name="product.name" value=(product.name)! required="true" maxlength="100" style="width:250px"/]
    [@b.textfield label="规格" name="product.specification" value=product.specification required="false" maxlength="100" style="width:250px"/]
    [@b.textfield label="数量" name="product.amount" value=product.amount required="true" maxlength="10" check="match('integer').greaterThan(0)" style="width:50px" /]
    [@b.datepicker label="下单时间" name="product.createdAt" value=product.createdAt required="true" format="yyyy-MM-dd HH:mm"/]
    [@b.datepicker label="预计出货" name="product.planShippedOn" value=product.planShippedOn required="true" /]
    [@b.datepicker label="实际出货" name="product.shippedOn" value=product.shippedOn required="false" /]
    [@b.radios label="是否完结" name="product.finished" value=product.finished required="true" /]
    [@b.datepicker label="完结日期" name="product.finishedOn" value=product.finishedOn required="false" /]
    [@b.field label="所需环节"]
      [#assign categories= product.taskCategories/]
      [#list taskCategories?sort_by('code') as c]
     <label class="checkbox-inline"><input type="checkbox" name="taskCategoryId"  [#if categories?seq_contains(c)]checked="checked"[/#if] value="${c.id}">${c.name}</label>
     [/#list]
    [/@]
    [@b.textfield label="备注" name="product.remark" value=(product.remark?html)! required="false" maxlength="200" /]

    [@b.formfoot]
      [@b.submit value="提交"/]
    [/@]
  [/@]
[@b.foot/]
